name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Commit built files
      run: |
        git config --local user.name "HiteshDatt"
        git config --local user.email "hdk.hitesh26@gmail.com"
        git add .
        git commit -m "Build updated [skip ci]" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: master
